# roles/app_build/tasks/main.yml
---
- name: Start MySQL service asynchronously
  service:
    name: mysql
    state: started
  async: 120
  poll: 0
  register: mysql_start_job
  when: "'dev' in group_names"

- name: Wait for MySQL service to be started
  async_status:
    jid: "{{ mysql_start_job.ansible_job_id }}"
  register: mysql_start_result
  until: mysql_start_result.finished
  retries: 12
  delay: 10
  when: "'dev' in group_names"

- name: Wait for MySQL port to be open
  wait_for:
    host: "{{ mysql_host }}"
    port: "{{ mysql_port }}"
    timeout: 300
  when: "'dev' in group_names"

- name: Set current build timestamp
  set_fact:
    build_time: "{{ lookup('pipe', 'date -u +%Y%m%dT%H%M%SZ') }}"
  when: build_env in ['prod', 'dev']

- name: Save build_time to file
  copy:
    content: "{{ build_time }}"
    dest: /tmp/build_time.txt
  when: build_env in ['prod', 'dev']

- import_tasks: deploy_env.yml
- import_tasks: cleanup.yml # cleanup before build
- include_tasks: build.yml
  vars:
    build_time: "{{ build_time }}"
- import_tasks: cleanup.yml # again (clears old)

# - import_tasks: up.yml
