# roles/efs_mount/tasks/main.yml
---
- name: Ensure /mnt/efs directory exists
  file:
    path: /mnt/efs
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: "0755"

- name: Install NFS utilities
  apt:
    name: nfs-common
    state: present
  become: yes

- name: Mount EFS using DNS
  mount:
    path: /mnt/efs
    src: "fs-0234f505cea7b18cd.efs.eu-north-1.amazonaws.com:/"
    fstype: nfs4
    opts: defaults,_netdev
    state: mounted

- name: Ensure EFS mount persists in fstab
  mount:
    path: /mnt/efs
    src: "fs-0234f505cea7b18cd.efs.eu-north-1.amazonaws.com:/"
    fstype: nfs4
    opts: defaults,_netdev
    state: present
