# roles/nginx_config/tasks/prod/main.yml
---
- name: Deploy nginx config for prod
  template:
    src: nginx_prod.conf.j2
    dest: /etc/nginx/sites-available/serpent_surge
    mode: 0644
  when: "'prod' in group_names"
  notify: Reload nginx

- name: Enable nginx site by symlink
  become: yes
  file:
    src: /etc/nginx/sites-available/serpent_surge
    dest: /etc/nginx/sites-enabled/serpent_surge
    state: link
  notify: Reload nginx

- name: Remove default nginx site if exists
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: Reload nginx

- name: Check nginx syntax
  command: nginx -t
  register: nginx_test
  changed_when: false
  failed_when: nginx_test.rc != 0
