---
# ansible/playbooks/playbook_app_build.yml
- hosts: all
  become: yes
  gather_facts: no
  pre_tasks:
    - name: Load env-specific vars
      include_vars: "../group_vars/{{ build_env | default('dev') }}.yml"
  roles:
    - role: app_build

- hosts: prod
  become: yes
  gather_facts: no
  pre_tasks:
    - name: Load env-specific vars
      include_vars: "../group_vars/{{ build_env | default('prod') }}.yml"
  roles:
    - role: app_build
