# playbooks/playbook_base_setup.yml
---
# Development Ubuntu (local)
- name: Base system setup (test locally)
  hosts: dev
  connection: local
  become: yes
  vars:
    build_env: dev
  vars_files:
    - ../group_vars/dev.yml
    - ../group_vars/all.yml
  roles:
    - system_dependencies
    - docker_install
    - nginx_install
  post_tasks:
    - name: Verify installations
      block:
        - name: Check AWS CLI version
          command: aws --version
          register: aws_version

# Production Ubuntu (remote)
- name: Base system setup and update prod
  hosts: prod
  remote_user: ubuntu
  become: yes

  pre_tasks:
    - name: Update system packages
      apt:
        update_cache: yes
        upgrade: dist
        cache_valid_time: 3600
      register: system_update

    - name: Reboot if kernel was updated
      reboot:
        msg: "Rebooting due to kernel update"
        pre_reboot_delay: 5
      when: system_update.changed and 'linux-image' in system_update.stdout

    - name: Install Python3 + pip
      apt:
        name:
          - python3
          - python3-pip
        state: present
        update_cache: yes

    - name: Install Ansible package
      apt:
        name: ansible
        state: latest
        update_cache: yes

    - name: Check requirements.yml presence on remote dev
      stat:
        path: "{{ playbook_dir }}/../requirements.yml"
      register: req_file
      run_once: true

    - name: Show requirements.yml status
      debug:
        msg: "requirements.yml exists: {{ req_file.stat.exists }}"
      run_once: true

  roles:
    - system_dependencies
    - docker_install
    - nginx_install

  post_tasks:
    - name: Verify installations
      block:
        - name: Check AWS CLI version
          command: aws --version
          register: aws_version
