# ansible/roles/nginx_install/tasks/main.yml
---
- name: Install nginx
  apt:
    name: nginx
    state: present
    update_cache: yes
  tags: nginx_install

- name: Test nginx config before starting
  command: nginx -t
  register: nginx_test
  failed_when: nginx_test.rc != 0
  changed_when: false

- name: Ensure nginx is enabled and running
  systemd:
    name: nginx
    state: started
    enabled: true
    daemon_reload: yes
