# installs nginx, copies config templates, restarts service

---
- name: Install required packages
  apt:
    name:
      - docker.io
      - docker-compose
      - nginx
    state: present
    update_cache: yes

- name: Ensure docker service is running
  systemd:
    name: docker
    state: started
    enabled: yes

- name: Copy nginx reverse proxy config
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/serpent_surge
    mode: '0644'
  notify: Reload nginx

- name: Enable nginx site
  file:
    src: /etc/nginx/sites-available/serpent_surge
    dest: /etc/nginx/sites-enabled/serpent_surge
    state: link
  notify: Reload nginx

- name: Remove default nginx site if exists
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: Reload nginx

- name: Build frontend docker image
  docker_image:
    path: "{{ docker_frontend_path }}"
    name: serpent-frontend
    state: present

- name: Build backend docker image
  docker_image:
    path: "{{ docker_backend_path }}"
    name: serpent-backend
    state: present

- name: Run frontend container
  docker_container:
    name: serpent-frontend
    image: serpent-frontend
    state: started
    restart_policy: always
    ports:
      - "80:80"

- name: Run backend container
  docker_container:
    name: serpent-backend
    image: serpent-backend
    state: started
    restart_policy: always
    ports:
      - "3000:3000"
