# roles/nginx_config/tasks/dev/main.yml
---
# For container-only reverse proxy, listens on 8080 (no host Nginx provisioning)
# - name: Render nginx config for docker container (local dev only)
#   template:
#     src: nginx_docker.conf.j2
#     dest: /data/serpent-surge-infra/nginx.conf
#     mode: "0644"
#   when: "'dev' in group_names and not nginx_as_host_proxy | default(false)"

# For host-level reverse proxy, listens on 80/443
- name: Deploy nginx config for dev
  template:
    src: nginx_dev.conf.j2
    dest: /etc/nginx/sites-available/serpent_surge
    mode: 0644
  when: "'dev' in group_names"
  notify: Reload nginx

- name: Enable nginx site by symlink
  become: yes
  file:
    src: /etc/nginx/sites-available/serpent_surge
    dest: /etc/nginx/sites-enabled/serpent_surge
    state: link
  notify: Reload nginx

- name: Remove default nginx site if exists
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: Reload nginx

- name: Check nginx syntax
  command: nginx -t
  register: nginx_test
  changed_when: false
  failed_when: nginx_test.rc != 0
