# serpent-surge-infra\.github\workflows\ansible-lint.yml
name: Ansible Lint and Syntax Check

on:
  push:
    branches:
      - main
      - infra-ci
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install ansible-lint
        run: |
          python -m pip install --upgrade pip
          pip install ansible-lint

      - name: Run ansible-lint
        run: ansible-lint ./ansible/*.yml

  syntax-check:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Run syntax check
        run: |
          for f in ./ansible/*.yml; do
            if [ "$(basename $f)" != "requirements.yml" ]; then
              ansible-playbook --syntax-check "$f"
            fi
          done
