# roles/docker_install/tasks/main.yml
---
- name: Ensure /etc/apt/keyrings exists
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"
  become: yes

- name: Download Docker GPG key and dearmor it
  shell: |
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  args:
    creates: /etc/apt/keyrings/docker.gpg
  become: yes

- name: Set permissions on Docker GPG key
  file:
    path: /etc/apt/keyrings/docker.gpg
    mode: "0644"
  become: yes

- name: Add Docker apt repository (force jammy on noble)
  ansible.builtin.copy:
    content: |
      deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu jammy stable
    dest: /etc/apt/sources.list.d/docker.list
    mode: "0644"
  become: yes

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
  become: yes

- name: Install Docker packages
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
  become: yes

- name: Enable and start Docker
  ansible.builtin.systemd:
    name: docker
    enabled: yes
    state: started
  become: yes

- name: Add ubuntu user to docker group
  ansible.builtin.user:
    name: ubuntu
    groups: docker
    append: yes
  become: yes

- name: Check Docker Compose version
  ansible.builtin.shell: docker compose version
  register: compose_version
  become: yes

- name: Show Docker Compose version
  ansible.builtin.debug:
    msg: "{{ compose_version.stdout }}"
